import copy
import math

# ===============================
# 전역 변수 및 기본 설정
# ===============================

# 1번 위치 위쪽 좌표
pos1_pose_up = posx(574.07, 149.69, 340.0, 0.0, -180.0, 0.0)

# 3번 위치 위쪽 좌표
pos3_pose_up = posx(276.04, 147.85, 340.75, 0.0, -180.0, 0.0)

# 2번 위치 위쪽 좌표
# pos2_pose_up = posx(274.45, -151.64, 340.75, 0.0, -180.0, 0.0)

# 외력 감지 기준값
FORCE_THRESHOLD = - 5.0

# 물체를 잡기 위해 접촉 위치에서 위로 올릴 높이
GRIPPER_Z_OFFSET = 40.0

# 아래로 내려갈 거리
DOWN_DISTANCE = 500.0
DOWN_SPEED = 30
DOWN_ACC = 30

CONTACT_CHECK_PERIOD = 0.02

# 그리퍼 상태
# 0 : 물체를 잡고 있지 않은 상태
# 1 : 물체를 잡고 있는 상태
gripper_status = 0

# compliance 전용 stiffness
CUSTOM_STIFFNESS = [3000, 3000, 300, 400, 400, 400]

# ===============================
# 기어 삽입 관련 설정
# ===============================

FORCE_TARGET_Z = -20.0
FORCE_MARGIN = 5.0
FORCE_DIRECTION = [0, 0, 1, 0, 0, 0]

INSERT_TARGET_Z = 270.0
INSERT_Z_TOLERANCE = 3.0

INSERT_SUCCESS_Z_THRESHOLD = 285.0

# ===============================
# 그리퍼 초기화 함수
# ===============================

def gripper_init():
    global gripper_status

    # 1번 위치 위쪽으로 이동
    movel(pos1_pose_up, 50, 50)

    # 그리퍼 열기
    open_gripper()

    return


# ===============================
# 그리퍼 열기 함수
# ===============================

def open_gripper():
    global gripper_status

    set_digital_output(1, OFF)
    set_digital_output(2, ON)
    
    wait_digital_input(2,1)

    gripper_status = 0

    return


# ===============================
# 그리퍼 닫기 함수
# ===============================

def close_gripper(contact_pos):
    global gripper_status

    # 접촉 위치 복사
    grip_pos = copy.deepcopy(contact_pos)

    # 접촉 위치에서 살짝 위로 이동해서 그리퍼가 잡을 수 있게 보정
    grip_pos[2] += GRIPPER_Z_OFFSET

    # 보정 위치로 이동
    movel(grip_pos, 50, 50)

    # 그리퍼 닫기
    set_digital_output(2, OFF)
    set_digital_output(1, ON)
    
    wait_digital_input(1,1)

    gripper_status = 1

    return


# ===============================
# 아래로 내려가다가 외력이 감지되면 멈추는 함수
# ===============================

def move_down_until_contact(up_pose, speed=DOWN_SPEED, acc=DOWN_ACC):
    # 현재 상단 위치 복사
    down_pose = copy.deepcopy(up_pose)

    # 아래 방향으로 충분히 내려갈 목표 위치 설정
    down_pose[2] -= DOWN_DISTANCE

    # 아래 방향으로 비동기 이동 시작
    amovel(down_pose, speed, acc)

    while True:
        # 외력 센싱
        force_ext = get_tool_force(DR_BASE)
        force_z = force_ext[2]

        # 현재 위치 확인
        current_pos = get_current_posx()[0]
        current_z = current_pos[2]

        # Z축 외력 감지
        if force_z > FORCE_THRESHOLD:
            stop(DR_SSTOP)
            contact_pos = get_current_posx()[0]
            return contact_pos

        # 혹시 외력이 감지되지 않고 너무 아래까지 내려간 경우 안전 정지
        if current_z <= down_pose[2]:
            stop(DR_SSTOP)
            return None

        wait(CONTACT_CHECK_PERIOD)


# ===============================
# 특정 위치에서 물체를 잡는 함수
# ===============================

def pick_at(up_pose):
    global gripper_status

    # 해당 위치 위쪽으로 이동
    movel(up_pose, 50, 50)

    # Pick 동작에서도 부드럽게 접촉하기 위해 compliance 활성화
    task_compliance_ctrl(CUSTOM_STIFFNESS)

    # 아래로 내려가다가 외력 감지
    contact_pos = move_down_until_contact(up_pose, DOWN_SPEED, DOWN_ACC)

    # compliance 비활성화
    release_compliance_ctrl()

    # 접촉 실패 시 복귀
    if contact_pos is None:
        movel(up_pose, 50, 50)
        return False

    # 물체를 잡고 있지 않은 상태라면 물체 잡기
    if gripper_status == 0:
        close_gripper(contact_pos)

    # 잡은 상태로 다시 위쪽 위치로 이동
    movel(up_pose, 50, 50)

    return True

# 
def move_down_rotate(up_pose):
    global force
    global force_derection

    fail_count = 0

    task_compliance_ctrl(CUSTOM_STIFFNESS)

    
    down_pose = copy.deepcopy(up_pose)

    # 아래 방향으로 충분히 내려갈 목표 위치 설정
    down_pose[2] -= DOWN_DISTANCE
    
    # 아래 방향으로 비동기 이동 시작
    amovel(down_pose, DOWN_SPEED, DOWN_ACC)

    while True:
        # 외력 센싱
        force_ext = get_tool_force(DR_BASE)
        force_z = force_ext[2]

        if force_z > FORCE_THRESHOLD:
            stop(DR_SSTOP)
            break

        wait(CONTACT_CHECK_PERIOD)

    # Z축 아래 방향으로 일정 힘을 가함
    set_desired_force(
        [0, 0, FORCE_TARGET_Z, 0, 0, 0],
        FORCE_DIRECTION
    )
    
    while fail_count <= 5:
        success = False
        amove_periodic(amp = [0, 0, 0, 0, 0, 4], period = 0.5, atime = 0.1, repeat = 10, ref = DR_TOOL)
        mwait(0)
        current_pos = get_current_posx()[0]
        current_z = current_pos[2]

        if current_z <= (INSERT_TARGET_Z + INSERT_Z_TOLERANCE):
            success = True
        else:
            print("Gear insertion failed.")
            stop(DR_SSTOP)

        if success:
            release_force(0.5)
            release_compliance_ctrl()
            open_gripper()
            return True

        else:
            fail_count += 1

    tp_popup("이물질 제거해줘", pm_type=DR_PM_WARNING, button_type=0)
    return False

# ===============================
# 기어 삽입용 Place 함수
# ===============================
def place_at(up_pose):
    global gripper_status

    # 해당 위치 위쪽으로 이동
    movel(up_pose, 50, 50)

    # 아래로 내려가다가 외력이 감지되면 정지하고 접촉 위치 반환
    move_down_rotate(up_pose)


    movel(up_pose, 50, 50)

    return


# ===============================
# 메인 반복 동작
# ===============================
def start():
    # 초기 위치 이동 및 그리퍼 초기화
    gripper_init()

    # 1번 위치에서 물체 잡기
    pick_success = pick_at(pos1_pose_up)

    if pick_success == False:
        print("Pick at position 1 failed.")
        break

    # 2번 위치에 기어 삽입
    place_success = place_at(pos2_pose_up)

    if place_success == False:
        print("Gear place at position 2 failed.")
        break

def main():

    while 1:
        x, y, z, _, _, _= get_tool_force(DR_BASE, 0)
        z += 10
        
        impact_force = math.sqrt(x**2 + y**2 + z**2)

        if impact_force >= 20:
            start()
            break


# ===============================
# 프로그램 실행
# ===============================

main()